###############################################################################
#                             APPLICATION CONFIG                              #
###############################################################################

# Development options
# debug: true

# LDAP
security:
  ldap:
    url:
    base:
    pattern:

spring:
  # AOP
  aop:
    proxy-target-class: false

# Management
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,caches,auditevents
    enabled-by-default: false
    auditevents:
      enabled: true