version: '3'
services:
    auth-server:
        image: osixia/openldap:1.1.11
        container_name: ldap-auth-server
        volumes:
          - ./imports:/ldifs
        ports:
            - "1389:1389"
            - "1636:1636"
        environment:
            LDAP_ORGANISATION: "bernardomg.com organization"
            LDAP_DOMAIN: "bernardomg.com"
            LDAP_ADMIN_PASSWORD: "admin"
    auth-server-seed:
        image: osixia/openldap:1.1.11
        volumes:
            - ./imports:/ldif_files
        links:
            - auth-server
        entrypoint: '/ldif_files/importData.sh'
    ws:
        depends_on:
            - auth-server
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        container_name: ldap-ws
        ports:
            - "8080:8080"
            - "8000:8000"
        environment:
            # LDAP
            - spring.ldap.url=ldap://host.docker.internal:1389/dc=bernardomg,dc=com
            - spring.ldap.base=ou=groups
            - spring.ldap.username=cn=admin,dc=bernardomg,dc=com
            - spring.ldap.password=admin
