version: '3'
services:
  ldap-auth-server:
    image: bitnami/openldap:2.6.8
    container_name: ldap-auth-server
    volumes:
      - ./imports:/ldifs
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      LDAP_ROOT: "dc=bernardomg,dc=com"
      LDAP_USER_DC: "bernardomg"
      LDAP_GROUP: "people"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_ADMIN_PASSWORD: "admin"
    networks:
      - auth
  ldap-auth-server-seed:
    image: osixia/openldap:1.1.11
    volumes:
      - ./imports:/ldif_files
    entrypoint: '/ldif_files/importData.sh'
    networks:
      - auth
  ldap-ws:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - ldap-auth-server
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 60s
    environment:
      # LDAP
      - security.ldap.url=ldap://ldap-auth-server:1389/dc=bernardomg,dc=com
      - security.ldap.base=ou=groups
      - security.ldap.pattern=uid={0},ou=people
    networks:
      - auth
networks:
  auth:
